# Generated by Django 3.2.13 on 2022-05-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220430_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='image',
        ),
        migrations.AddField(
            model_name='word',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
