# Generated by Django 3.2.13 on 2022-05-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20220508_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
